from RadianceMethod.processing.DataExtractor import DataExtractor

test = DataExtractor()
test.set_experiment_name("Testexperiment")
test.set_image_dir('/Users/kristianboerger/repos/RadianceMethod/test_images')
test.set_results_dir('/Users/kristianboerger/repos/RadianceMethod/test_results')
test.set_camera_position(0,0,0)
test.set_image_series(9682,9686)
test.set_image_file_format('raw')
# test.set_image_name_string('DSC{:05d}.JPG')
test.set_image_name_string('DSC{:05d}.ARW')
test.set_reference_image_id(9682)
test.show_reference_image(1)
test.set_dark_roi_pixel_bounds((2440, 1984), (2440, 557))
test.set_light_roi_pixel_bounds((2483, 1984), (2483, 557))
test.set_roi_parameters(10, 100)
test.set_dark_roi_real_bounds((0,4,0),(0,4,3))
test.set_light_roi_real_bounds((0.1,4,0),(0.1,4,3))
test.calc_geometrics()
test.plot_reference_image_with_rois(1)
test.process_image_data()
